sudo: required

env:
  global:
  - ENCRYPTION_LABEL: dcc9512392ad

addons:
  ssh_known_hosts:
  - scrimmagesim.org
  
before_install:
- sudo apt-get install tar

dist: trusty

language: cpp

services:
- docker

script:
- docker build -t $DOCKER_USERNAME/scrimmage:$TRAVIS_BUILD_NUMBER -f ./ci/dockerfiles/ubuntu-16.04 .

after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && 
      [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    export REPO=$DOCKER_USERNAME/scrimmage
    docker tag $REPO:$TRAVIS_BUILD_NUMBER $REPO:latest
    docker create --name mycontainer $REPO:latest
    docker cp mycontainer:/root/scrimmage/build/docs ./doc_output
    bash ./ci/scripts/deploy-docs.sh
    docker push $REPO
  fi

notifications:
  email:
    on_success: change
    on_failure: always
