sudo: required

env:
  global:
  - ENCRYPTION_LABEL: dcc9512392ad

addons:
  ssh_known_hosts:
  - scrimmagesim.org
  
before_install:
- sudo apt-get install tar

dist: trusty

language: cpp

services:
- docker

script:
- docker build -t $DOCKER_USERNAME/scrimmage:latest -f ./ci/dockerfiles/ubuntu-16.04 .

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker create --name mycontainer $DOCKER_USERNAME/scrimmage:latest
- docker cp mycontainer:/root/scrimmage/build/docs ./doc_output
- bash ./ci/scripts/deploy-docs.sh
- docker push $DOCKER_USERNAME/scrimmage:latest

notifications:
  email:
    on_success: change
    on_failure: always
