sudo: required

env:
  global:
  - ENCRYPTION_LABEL: dcc9512392ad

addons:
  ssh_known_hosts:
  - scrimmagesim.org
  
before_install:
- sudo apt-get install tar

dist: xenial

language: cpp

services:
- docker

script:
- docker build -t $DOCKER_USERNAME/scrimmage:$TRAVIS_BUILD_NUMBER -f ./ci/dockerfiles/ubuntu-16.04 .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export REPO=$DOCKER_USERNAME/scrimmage
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER $REPO:$TAG
  - docker create --name mycontainer $REPO:$TAG
  - docker cp mycontainer:/root/scrimmage/build/docs ./doc_output
  - if [[ "$TAG" == "latest" ]]; then bash ./ci/scripts/deploy-docs.sh; fi
  - docker push $REPO

notifications:
  email:
    on_success: change
    on_failure: always
